base_model: Abner0803/Qwen3-1.7B-msmarco-text-100k-with_pseudo_queries

datasets:
  - path: /semantic-search-pvc/users/lala/ICLGR_local/data/msmarco-docquery-100k-3shot_v3_noise_heavy/train_3shot.jsonl
    type: chat_template
    chat_template: tokenizer_default_fallback_chatml
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      assistant:
        - assistant
        - gpt
        - model
      user:
        - user
        - human
      system:
        - system

roles_to_train: ["assistant"]
train_on_eos: "turn"

shuffle_merged_datasets: true
output_dir: ./checkpoint/Qwen3-1.7B-icl-3shot-v3-noise-heavy-1e-4-8epochs
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true
flash_attention: true
xformers_attention: false
flex_attention: false
sdp_attention: false

gradient_accumulation_steps: 8
micro_batch_size: 8
dataloader_num_workers: 6
num_epochs: 8

optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-4
warmup_ratio: 0.1
weight_decay: 0.0
bf16: true
tf32: false
gradient_checkpointing: true

logging_steps: 50
save_strategy: epoch
save_total_limit: 8

wandb_project: "ICLGR"
wandb_entity: "lala83"
wandb_watch: "gradients"
wandb_name: "qwen-1.7b-icl-3shot-v3-noise-heavy-1e-4-8epochs"
wandb_log_model: "checkpoint"

val_set_size: 0.0
