base_model: Qwen/Qwen3-1.7B-Base

datasets:
  - path: ./data/nq_text_title_axolotl/train_with_pseudo_axolotl.jsonl
    type: chat_template
    chat_template: tokenizer_default_fallback_chatml
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      assistant:
        - assistant
        - gpt
        - model
      user:
        - user
        - human
      system:
        - system

roles_to_train: ["assistant"]
train_on_eos: "turn"

shuffle_merged_datasets: true
output_dir: ./checkpoint/Qwen3-1.7B-nq-text-title-with_pseudo-lr1e-4-10epochs-v2
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true
flash_attention: false
xformers_attention: false
flex_attention: false
sdp_attention: true

gradient_accumulation_steps: 16
micro_batch_size: 8
dataloader_num_workers: 2
num_epochs: 15

optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-4
warmup_ratio: 0.1
weight_decay: 0.0
bf16: true
tf32: false
gradient_checkpointing: true

logging_steps: 50
save_strategy: epoch
save_total_limit: 3

special_tokens:
  eos_token: <|im_end|>

wandb_project: "ICLGR-NQ"
wandb_entity: "abnerden0803-national-taiwan-university"
wandb_name: "qwen3-1.7b-nq-text-title-pseudo-lr1e-4-10epochs-v2"
wandb_log_model:
wandb_watch:

val_set_size: 0.0
