base_model: Abner0803/Qwen3-1.7B-Base-msmarco-100k-11000

datasets:
  - path: /semantic-search-pvc/users/lala/ICLGR_project/ICLGR/data/msmarco-docquery-sid-3shot/train_3shot.jsonl  
    type: chat_template
    chat_template: tokenizer_default_fallback_chatml
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      assistant:
        - assistant
        - gpt
        - model
      user:
        - user
        - human
      system:
        - system

roles_to_train: ["assistant"]
train_on_eos: "turn"

streaming: false
streaming_multipack_buffer_size: 10000
shuffle_merged_datasets: true
output_dir: ./checkpoint/Qwen3-1.7B-icl-sid-3shot-1e-4-3epochs
sequence_len: 2048
sample_packing: true
flash_attention: true
xformers_attention: false
flex_attention: false
sdp_attention: false
# overrides_of_model_config:
#   _attn_implementation: "sdpa"

gradient_accumulation_steps: 4
micro_batch_size: 8
dataloader_num_workers: 6
num_epochs: 3

optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-4
warmup_ratio: 0.1
weight_decay: 0.0
bf16: true
tf32: false
gradient_checkpointing: true

logging_steps: 50
save_strategy: steps
save_steps: 500
save_total_limit: 3

wandb_project: "ICLGR-MSMARCO"
wandb_entity: "lala83"
wandb_watch:
wandb_name: "qwen3-1.7b-icl-sid-3shot-3epochs"
wandb_log_model:

special_tokens:
  # Explicitly set EOS token to ensure proper stopping during generation
  eos_token: "<|im_end|>"

val_set_size: 0.0
