model_path: "ICLGR_local/checkpoint/Qwen3-1.7B-icl-3shot-position-template-v3-pseudo-1e-4-8epochs/checkpoint-840"
train_file: "./data/uni_test/train_3shot.jsonl"
new_file: "./data/uni_test/test_3shot.jsonl"
num_beams: 10
num_return: 10
max_new_tokens: 50
no_trie: false
mode: "file"
query_file: "./data/uni_test/train_3shot.jsonl"
max_samples: 50
