input_path: "./data/msmarco-ICL-100k"
zs_input_path: "./data/msmarco_text-with_pseudo_query-100k-gr/train.jsonl"
dataset_name: "msmarco"
n_shot: 3
output_dir: "./data/msmarco-docquery-100k-3shot_v3_hard_neg_s10"

zs_noise: false
hard_negative: true
hard_negative_k: 20

type_ratios:
  doc_pos_front: 0.125
  doc_pos_back:  0.125
  stage1: 0.1                    # 10% of original stage1 (≈47.6k retrieval + 8.2k indexing)
