input_path: "./data/msmarco/"
dataset_name: "msmarco"
n_shot: 3
output_dir: "./data/msmarco-docquery-100k-instruct"

type_ratios:
  doc_pos_front: 0.125   # 1/8
  doc_pos_back:  0.125   # 1/8
  all_noise:     1.0     # 8/8
  zero_shot:     1.0     # 8/8
