input_path: "./data/msmarco-sample"
dataset_name: "msmarco"
n_shot: 3
output_dir: "./data/msmarco-sample-docquery-sid-3shot"

type_ratios:
  mem_retrieval: 0.5
  mem_indexing:  0.5
  ctx_match:     0.5
  ctx_nomatch:   1

# test split has no indexing docs, so mem_indexing budget is reallocated
test_type_ratios:
  mem_retrieval: 0.5
  mem_indexing:  0
  ctx_match:     0.5
  ctx_nomatch:   1
