input_path: "./data/msmarco-item-id"
zs_input_path: "./data/msmarco_text-with_pseudo_query-100k-gr/train_with_pseudo.jsonl"
dataset_name: "msmarco"
n_shot: 3
output_dir: "./data/msmarco-item-id-3shot_v4"

type_ratios:
  context_dependent: 1.0       # Every query gets one context-dependent sample
  all_noise:     1.0           # Every query gets one all-noise sample

retrieval_hard_neg: true
